### ISSUE TITLE
Issues with Modal scrolling/overflow sizing.

### ISSUE THREAD

**Issue by andrewheppner** [rackt/react-modal#102]
Hi guys,

I'm having an issue with a simple modal that I am trying to implement in a react/flux project. Here is the code for the Modal component (for testing purposes).

```
'use strict';

//Library Dependencies
const React = require('react');
const Modal = require('react-modal');

const AmazonModal = React.createClass({

  render() {

    //Modal Config
    const customStyles = {
      content : {
        top: '50%',
        left: '50%',
        right: 'auto',
        bottom: 'auto',
        marginRight: '-50%',
        transform: 'translate(-50%, -50%)'
      },
      overlay: {
        zIndex: 10
      }
    };

    return (

      <Modal
        isOpen = { this.props.modalIsOpen }
        onRequestClose = { TBD }
        style = { customStyles } >

        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>
        <p>Content</p>

     </Modal>

    )
  },

  _closeModal() {
    this.props.closeModal();
  }

});

module.exports = AmazonModal;
```

Currently I have two Issues that I cannot solve: 

The Modal is rendering but I am unable to see the full content of the modal. I am unable to scroll through the content. When I scroll it simply scrolls through the greyed out content behind it. I tried playing with all overflow settings for the content/overlay...but had no luck getting the desired outcome.

1. I would like to be able to scroll through the content of the modal itself so that I can see all of the elements within.. 

2. With this much content within the modal the top and the bottom borders of the modal are not even visible within the window... they appear to be cut off from the browser viewport, and no matter how far you scroll up/down they do not become visible.

Any help would be greatly appreciated. Please let me know if I can provide anymore info for troubleshooting!
Thanks very much (i'm a newbie)

Andrew

**Comment by Ghosh** [comment]
@andrewheppner Hi Andrew, actually that is not an issue with react-modal or react for that matter. It's CSS positioning. 

Since the modal is absolutely positioned, it is out of the document bounds, in other words the document, does not know how big the modal is and has no idea that it is bigger than the document itself and therefore doesn't scroll.

This can be fixed by giving the modal a fixed height and setting the `overflow` property to `scroll`. Try the code below, I just tested it and it works perfectly.

```js
    var customStyles = {
      content : {
        top: '50%',
        left: '50%',
        right: 'auto',
        bottom: 'auto',
        marginRight: '-50%',
        transform: 'translate(-50%, -50%)',
        height: '500px', // <-- This sets the height
        overlfow: 'scroll' // <-- This tells the modal to scrol
      }
    };
```

**Comment by andrewheppner** [comment]
Thanks so much!
That did it.

Andrew

On Sun, Nov 15, 2015 at 12:43 PM, Indrashish Ghosh <notifications@github.com

**Comment by Khushboopandit** [comment]
hey!
I tried overflow for scrolling my popup but it doesn't work for me.
can you suggest me something else?

**Comment by fredcorn** [comment]
What if I don't want to make the content scrollable, instead I would like to scroll the body to see the overflow content?

**Comment by corysimmons** [comment]
@fredcorn It should be scrollable by default (since http://reactcommunity.org/react-modal/styles/classes.html#for-the-documentbody-and-html-tag `overflow` isn't set to `hidden` yet).

**Comment by corysimmons** [comment]
This is more complicated than the above solutions.

You have to have a fixed overlay. Content needs to be scrollable. Content needs to be centered regardless of amount of content (1 word or 10,000 words).

I'm using https://css-tricks.com/centering-in-the-unknown/ (oldie but goodie... seems to work better than flexbox).

![image](https://user-images.githubusercontent.com/224636/51711336-c8effe80-1ff9-11e9-8050-1311bfbd255d.png)

```css
.ReactModalPortal {
  position: relative;
  z-index: 9999;
}

.ReactModal__Body--open {
  overflow: hidden;
}

.ReactModal__Overlay {
  display: table;
  width: 100%;
  height: 100%;
  background: rgba(0, 0, 0, .5);
}

.ReactModal__Content {
  display: table-cell;
  vertical-align: middle;
  position: relative;
  left: 15vw;
  outline: none;

  > div {
    max-width: 70vw;
    max-height: 50vh;
    padding: 2rem;
    overflow: auto;
    border-radius: 2rem;
    background: white;
  }
}
```

```html
<ReactModal isOpen={true}>
  <div>
    <h1 className="heading">Yeee</h1>
    <p>
      Lorem ipsum...
    </p>
  </div>
</ReactModal>
```

**Comment by VirajBhagat2003** [comment]
Just use 'scrollable' inside modal it will help you from overflowing 
<Modal scrollable size='xl'>
</Modal>

**Comment by Tortillabudding** [comment]
@corysimmons https://stylesheets.space/questions/steps-for-ensuring-a-div-component-appears-on-top-of-any-other-component-like-h1-or-p
