### ISSUE TITLE
change z-index of the overlay?

### ISSUE THREAD

**Issue by shangsunset** [rackt/react-modal#110]
Because i have some component has z-index that is > 1, the overlay doesnt cover the whole window. is it possible to add an z-index to the overlay style? thanks.

**Comment by iColpitts** [comment]
Has this issue been fixed?

**Comment by diasbruno** [comment]
Hi @iColpitts, probably the best way to fix this is using css or override the styles [react-modal styles](https://github.com/reactjs/react-modal#styles).

**Comment by mecapetr** [comment]
Yes, this fix this, but there is another problem after this. If the content height of modal is bigger then screen height, scrolling with mouse wheel does not work.
