### ISSUE TITLE
Why are overlay styles not being applied the second time I open a modal

### ISSUE THREAD

**Issue by TomClarkson** [rackt/react-modal#26]
When I open and modal and close it and try to open it again the modal does not show because the overlay styles (position: fixed; left: 0px; right: 0px; top: 0px; bottom: 0px;) are not being added to then dom element the second time I open it. 

Could you please advise how I can fix this

![screen shot 2015-04-08 at 5 23 56 pm](https://cloud.githubusercontent.com/assets/2054503/7039308/1869fdde-de14-11e4-8bb4-e21a59576ba4.png)

**Comment by mzabriskie** [comment]
@TomClarkson it has been a while since you posed your question. Wondering if you are still seeing this behavior.

**Comment by TomClarkson** [comment]
I stopped using react-modal as I couldn't stop this behaviour. There must have been some conflict with the rest of our app but I couldn't track down the issue. Thanks anyway.
