### ISSUE TITLE
[Feature Request] Add class to app element when modal open

### ISSUE THREAD

**Issue by astephenb** [rackt/react-modal#29]
We would like to lock the app from scrolling when the modal is open. Currently we have a wrapper around `Modal` to set the class on our app element based on the `isOpen` prop.

**Comment by KyleAMathews** [comment]
Ran into the same problem. Will work on a patch for this Monday.

**Comment by KyleAMathews** [comment]
@astephenb created PR if you'd like to test.

**Comment by vinceprofeta** [comment]
@KyleAMathews Did this get merged?

**Comment by KyleAMathews** [comment]
Nope. This is the PR https://github.com/rackt/react-modal/pull/41

**Comment by bartimaeus** [comment]
@KyleAMathews I haven't seen any movement on this project in about 2 months. They must be really busy with the launch of the React training course.

**Comment by KyleAMathews** [comment]
@bartimaeus oh hey Eric! :)

Yeah, something like that. Though @mzabriskie isn't working with Michael and Ryan.

@mzabriskie any chance you can add more maintainers here?

**Comment by mzabriskie** [comment]
Sorry for the delay. Spent some time giving this project some much anticipated attention. Will be cutting a new release soon.

**Comment by KyleAMathews** [comment]
Thanks!
