### ISSUE TITLE
Invalid require syntax in dist?

### ISSUE THREAD

**Issue by DelvarWorld** [rackt/react-modal#33]
When I try to [load react-modal in a jsfiddle](http://jsfiddle.net/69z2wepo/7616/), I get `Uncaught Error: Script error for: react-modal`. According to [the doc page linked by the error](http://requirejs.org/docs/errors.html#scripterror), "This usually means there is a JavaScript syntax error or other execution problem running the script." It's using require 2.1.7 from CDNJS.

If I copy and paste the entire contents of the react-modal.js file into the jsfiddle above this line: `require(['react-modal'], function(Modal) {` the error it spits out is:

    Uncaught Error: Mismatched anonymous define() module: function (){var define,module,exports;return (function e(t,n,r){function s(o,u){if(!n[o])

and the error includes the entire contents of the script.

**Comment by zdfs** [comment]
Can you just update your config to this?

```javascript
requirejs.config({
    appDir: ".",
    baseUrl: "js",
    paths: { 
        'react-modal': ['http://andrewray.me/stuff/react-modal']
    },
    shim: {
        'react-modal': 'react'
    }
});
```

All I did was remove the `.js` file extension from the `paths` object. https://jsfiddle.net/p6n7hv3v/
