### ISSUE TITLE
Replacement for HTMLElement in code? 

### ISSUE THREAD

**Issue by DelvarWorld** [rackt/react-modal#34]
[This library uses the global `HTMLElement`](https://github.com/rackt/react-modal/blob/master/lib/components/Modal.js#L18) which only exists in DOM land. We mock our environment with JSDom, however this code is loaded at `require()` time before JSDom is instantiated, so the require fails and crashes execution. What about `React.PropTypes.object`, or `global.HTMLElement` (which wouldn't fail the `require()` and also fix the linting error in the file) or `typeof window === "undefined" ? React.PropTypes.object : global.HTMLElement` ?

**Comment by mzabriskie** [comment]
Resolved with #22
