### ISSUE TITLE
Remove warning when using classSet 

### ISSUE THREAD

**Issue by rafaelchiti** [rackt/react-modal#35]
On React 0.13 we are getting a warning.

`
Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset
`

If you are ok with clearing out this warning by either using plain js or use the dependency (https://www.npmjs.com/package/classnames I'm in favor of just plain js), I would be more than happy to submit a PR. 

Thanks!

**Comment by mzabriskie** [comment]
Resolved with #28
