### ISSUE TITLE
Does not work in strict mode

### ISSUE THREAD

**Issue by rlancer** [rackt/react-modal#59]
opacity is repeated

./~/simple-react-modal/build/styles.js
Module parse failed:/node_modules/simple-react-modal/build/styles.js Line 17: Duplicate data property in object literal not allowed in strict mode
You may need an appropriate loader to handle this file type.
|   opacity: 0,
|   transition: 'opacity 400ms ease-in',
|   opacity: 1,
|   pointerEvents: 'auto'
| };
 @ ./~/simple-react-modal/build/simple-modal.js 23:14-33

**Comment by zdfs** [comment]
Is this something you added? I don't see `styles.js` in the repo, so not sure how to reproduce this.

**Comment by rlancer** [comment]
Looks like it was another react modal repo ... Sorry for the confusion.
