### ISSUE TITLE
Pass inline styles?

### ISSUE THREAD

**Issue by devmanhinton** [rackt/react-modal#66]
Awesome library thanks for building!

Is there a way to pass on inline styles to the modal overlay?

I am using Radium / trying to avoid using css etc...

ie., this:
```js
<Modal style={myStyles}.../>
```
would pass the styles onto the modal overlay. I think this makes sense in react speak

**Comment by mzabriskie** [comment]
You can currently pass `style` prop, but it is applied to the modal content, not the overlay. Could add support for a `overlayStyle` prop, which would augment the `overlayClassName` prop.

**Comment by devmanhinton** [comment]
Sorry for the long delay - made a work around and kept going (ie., just added some `scss` :grinning: )

That would solve my problem. Not sure how big of a use case that is for you. Feel free to close this issue. It was meant only to ask the above question and also let you know this might be a use case.

**Comment by MinThaMie** [comment]
I think it would be awesome to have also overlayStyle since React and inlineStyles are more and more common practice :)
