### ISSUE TITLE
Support for React 0.14

### ISSUE THREAD

**Issue by globexdesigns** [rackt/react-modal#67]
The library currently doesn't work with React 0.14 due to the use of `react/lib/ExecutionEnvironment` which no longer exists.

**Comment by arasmussen** [comment]
react-modal also needs to use renderSubtreeIntoContainer instead of render in order for context to work properly. This is the last thing blocking my upgrade to 0.14rc.

**Comment by ggarek** [comment]
I tried the PR and it does not work for me. =(

I get these errors in  the console:

```
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

Uncaught Error: Invariant Violation: removeComponentAsRefFrom(...): Only a ReactOwner can have refs. You might be removing a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

Sadly, did not find a way to fix it yet.

And one more thing, may be it would be wiser to use [fbjs](https://github.com/facebook/fbjs) instead of exenv.

**Comment by conorhastings** [comment]
@ggarek facebook reccomends against using fbjs

> If you are consuming the code here and you are not also a Facebook project, be prepared for a bad time. APIs may appear or disappear and we may not follow semver strictly, though we will do our best to. This library is being published with our use cases in mind and is not necessarily meant to be consumed by the broader public. In order for us to move fast and ship projects like React and Relay, we've made the decision to not support everybody. We probably won't take your feature requests unless they align with our needs. There will be overlap in functionality here and in other open source projects.

**Comment by pycbouh** [comment]
So, 0.14 was officially released yesterday. Is there an ETA on when react-modal will be compatible with it?

**Comment by mzabriskie** [comment]
I believe that #78, and #79 will resolve this issue.
