### ISSUE TITLE
React peerDependency inquiry

### ISSUE THREAD

**Issue by sprjr** [rackt/react-modal#72]
Folks - 

Is there any reason that you peer-require `>=0.13.3` for this, and could `>=0.13.2` be used instead? I'm not sure what the react changes are from those versions. I unfortunately can't seem to get another dependency I have's latest version to work with our builds. Wondering if this is an option to update, or how much work would be involved?

I can do the legwork if you think there's a decent amount to do, or hold off on pulling this in to our apps until we can update that other module as well.

Thoughts?

Update: wondering if you're requiring anything in [this release specifically](https://github.com/facebook/react/blob/master/CHANGELOG.md#0133-may-8-2015)

**Comment by mzabriskie** [comment]
`0.13.3` is just arbitrary. I think that was the latest version available at the time we updated React last. Would you be able to use `0.14.0` in the near future? Our goal is to keep up with the latest React release.
