### ISSUE TITLE
React 0.14.0

### ISSUE THREAD

**Issue by YesaDyuss** [rackt/react-modal#77]
There is error when import

ERROR in ./~/react-modal/lib/components/Modal.js
Module not found: Error: Cannot resolve module 'react/lib/ExecutionEnvironment' in /home/yesa/Projects/sporta/node_modules/react-modal/lib/components
 @ ./~/react-modal/lib/components/Modal.js 2:27-68

**Comment by AmerShahnawazsc** [comment]
What's the ETA for this fix to be released ?

**Comment by mzabriskie** [comment]
Working on getting #78, and #79 merged, which will resolve this issue.

**Comment by miracle2k** [comment]
@mzabriskie Supposedly renderSubtreeIntoContainer should be used too, for context purposes. I am using this: https://github.com/miracle2k/react-modal/commit/acac059198afef3d8627d15dfe641d46e77c8442
