### ISSUE TITLE
Release with 0.14 Support

### ISSUE THREAD

**Issue by yashprit** [rackt/react-modal#86]
@mzabriskie @ryanflorence Guys could you please let's know when you can release react-modal with 0.14 support, required pull request is already merged https://github.com/rackt/react-modal/pull/81

**Comment by roth1002** [comment]
:+1:

**Comment by mzabriskie** [comment]
Let me look through the issues to see if we can get anything else in the release. I will try and get something out by this afternoon.

**Comment by tbaeg** [comment]
+1 @mzabriskie thanks for all the hard work!

**Comment by vonwao** [comment]
If you haven't done the release yet, may I suggest meteor support?  

It looks like it already should be in master branch, there was a merge in #70, but I'm not certain this fixes it completely.  See #73 for meteor error. 

I'd be happy to test it, as soon as I figure out how to install local npm module dependency in meteor.

**Comment by mzabriskie** [comment]
Just released 0.6.0, which includes support for react@0.14.0

**Comment by natorojr** [comment]
Sweet! Just confirmed the 0.6.0 release published to npm fixes my broken Webpack build. Testing functionality next.

**Comment by flskif** [comment]
It seems like something went wrong with build process: `dist/react-modal.js` got `17,874 additions` this version (https://github.com/rackt/react-modal/commit/1ff6a02c689e9fdc03616c4ab82ec53317f14c69). Looks like whole React got embedded!

**Comment by mzabriskie** [comment]
Yikes. I bet it's because I'm not setting `react-dom` as an external. I'll look into it.

**Comment by flskif** [comment]
I've created a pull request that fixes build https://github.com/rackt/react-modal/pull/87

**Comment by mzabriskie** [comment]
react-modal@0.6.1 fixes problem with ReactDOM being included in bundle.

**Comment by flskif** [comment]
Thanks, Matt!
